DROP TABLE IF EXISTS agencies;

DROP TABLE IF EXISTS calendar_dates;

DROP TABLE IF EXISTS routes;

DROP TABLE IF EXISTS shapes;

DROP TABLE IF EXISTS stop_times;

DROP TABLE IF EXISTS stops;

DROP TABLE IF EXISTS trips;

DROP EXTENSION IF EXISTS postgis CASCADE;
